# Generated by Django 5.1.4 on 2025-01-20 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productimage_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductSpecification',
            new_name='DokoonProductSpecification',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterModelOptions(
            name='dokoonproductspecification',
            options={'verbose_name': 'Product Specification', 'verbose_name_plural': 'Product Specifications'},
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='DokoonCategory',
        ),
        migrations.RenameModel(
            old_name='ProductSpecificationValue',
            new_name='DokoonProductSpecificationValue',
        ),
        migrations.RenameModel(
            old_name='ProductType',
            new_name='DokoonProductType',
        ),
        migrations.CreateModel(
            name='DokoonProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Required', max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Not Required', verbose_name='Description')),
                ('slug', models.SlugField(max_length=255)),
                ('regular_price', models.DecimalField(decimal_places=2, error_messages={'name': {'The Price Must Be Between 0 , 999,99'}}, help_text='Maximum 999.99', max_digits=5, verbose_name='Regular Price')),
                ('discount_price', models.DecimalField(decimal_places=2, error_messages={'name': {'The Discount Must Be Between 0 , 999,99'}}, help_text='Maximum 999.99', max_digits=5, verbose_name='Discount Price')),
                ('is_active', models.BooleanField(default=True, help_text='Change Product Visibility', verbose_name='Product Visibility')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.dokooncategory')),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='store.dokoonproducttype')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AlterField(
            model_name='dokoonproductspecificationvalue',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.dokoonproduct'),
        ),
        migrations.CreateModel(
            name='DokoonProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='images/default.png', help_text='Upload a Products Image', upload_to='images/', verbose_name='image')),
                ('alt_text', models.CharField(blank=True, help_text='Provide descriptive text for the image', max_length=255, null=True, verbose_name='Image Alternative Text')),
                ('is_feature', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_image', to='store.dokoonproduct')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
