# Generated by Django 5.1.5 on 2025-01-26 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_productspecification_dokoonproductspecification_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dokoonproduct',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='category', to='store.dokooncategory'),
        ),
    ]
